name: Publish to NuGet

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore
        run: dotnet restore --nologo

      - name: Build
        run: dotnet build -c Release --no-restore --nologo

      - name: Pack
        run: dotnet pack -c Release --no-build -o out --nologo

      - name: Verify package(s)
        run: ls -al out

      - name: Push package(s) to NuGet.org
        run: |
          for pkg in out/*.nupkg; do
            echo "Pushing $pkg"
            dotnet nuget push "$pkg" \
              -k "${{ secrets.BLADE_STATE_NUGET_API_KEY }}" \
              -s "https://api.nuget.org/v3/index.json" \
              --skip-duplicate \
              --force-english-output
          done

