name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Package
      - name: Create NuGet package
        run: dotnet pack --configuration Release --no-build -o out

      # Publish to NuGet
      - name: Publish to NuGet
        run: dotnet nuget push "out/*.nupkg" \
        --api-key ${{ secrets.BLADE_STATE_NUGET_API_KEY }} \
        --source "https://api.nuget.org/v3/index.json" \
        --skip-duplicate

